C#/CaseStudy/CaseStudy/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using CaseStudy.Utils;
using CaseStudy.Models;
using System.Collections.Generic;

namespace CaseStudy.Controllers
{
    public class CartController : Controller
    {
        AppDbContext _db;
        public CartController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult ClearCart() // clear out current items
        {
            HttpContext.Session.Remove(SessionVars.Cart);
            HttpContext.Session.Set<String>(SessionVars.Message, "Cart Cleared");
            return Redirect("/Home");
        }
        // Add the cart, pass the session variable info to the db
        public ActionResult AddCart()
        {
            CartModel model = new CartModel(_db);
            Tuple<int, int> retVals;
            string retMessage = "";
            try
            {
                Dictionary<string, object> cartItems = HttpContext.Session.Get<Dictionary<string, object>>(SessionVars.Cart);
                retVals = model.AddCart(cartItems, HttpContext.Session.GetString(SessionVars.User));
                if (retVals.Item1 > 0) // Cart Added
                {
                    retMessage = "Cart " + retVals.Item1 + " Created!" + ((retVals.Item2 == 1) ?  " Some goods were backordered." : "") ;
                }
                else // problem
                {
                    retMessage = "Cart not added, try again later";
                }
            }
            catch (Exception ex) // big problem
            {
                retMessage = "Cart was not created, try again later! - " + ex.Message;
            }
            HttpContext.Session.Remove(SessionVars.Cart); // clear out current cart once persisted
            HttpContext.Session.SetString(SessionVars.Message, retMessage);
            return Redirect("/Home");
        }
        public IActionResult List()
        {
            // they can't list Carts if they're not logged on
            if (HttpContext.Session.GetString(SessionVars.User) == null)
            {
                return Redirect("/Login");
            }
            return View("List");
        }

        [Route("[action]")]
        public IActionResult GetCarts()
        {
            CartModel model = new CartModel(_db);
            return Ok(model.GetAll(HttpContext.Session.GetString(SessionVars.User)));
        }

        [Route("[action]/{tid:int}")]
        public IActionResult GetCartDetails(int tid)
        {
            CartModel model = new CartModel(_db);
            return Ok(model.GetCartDetails(tid, HttpContext.Session.GetString(SessionVars.User)));
        }
    }
}

C#/CaseStudy/CaseStudy/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CaseStudy.Models;

namespace CaseStudy.Controllers
{
    public class DataController : Controller
    {
        AppDbContext _ctx;
        public DataController(AppDbContext context)
        {
            _ctx = context;
        }
        public IActionResult Index()
        {
            DataUtility util = new DataUtility(_ctx);
            string msg = "";
            var json = System.IO.File.ReadAllText(@"D:\\Semester 4 Folder\\INFO-3067 ASP.NET\\CaseStudy\\JSON\\Data.json");
            try
            {
                msg = (util.loadInformationFromFileToDb(json)) ? "tables loaded" : "problem loading tables";
            }
            catch (Exception ex)
            {
                msg = ex.Message;
            }
            ViewData["msg"] = msg;
            return View();
        }
    }
}

C#/CaseStudy/CaseStudy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Case Study</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css" asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <span class="pull-right" style="padding-right:5%;padding-top:1%;color:white">@Context.Session.GetString(SessionVars.LoginStatus)</span>
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Branch" asp-action="Index">Branches</a></li>
                    <!--Less useful after database is left to Azure-->
                    <!--<li><a asp-area="" asp-controller="Data" asp-action="Index">Data Routines</a></li>-->
                    <li><a asp-area="" asp-controller="Brand" asp-action="Index">Brands</a></li>
                    <li><a asp-area="" asp-controller="Cart" asp-action="List">Cart</a></li>
                    <li><a asp-area="" asp-controller="Register" asp-action="Index">Register</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Logoff">Logoff</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="footer" style="margin-left:10%;margin-top:10%;">
        <p>&copy; 2018 - Info3067</p>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js" asp-fallback-src="~/lib/jquery/dist/jquery.min.js" asp-fallback-test="window.jQuery" crossorigin="anonymous" integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js" asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" crossorigin="anonymous" integrity="sha384-
Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>