C#/CaseStudy/CaseStudy/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CaseStudy.Models
{
    public class RegisterViewModel
    {
        // Username - Age(int) - Mailcode - Country - CreditcardType - Region
        [Required(ErrorMessage = "Username is required.")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Firstname is required.")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "Lastname is required.")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [CompareAttribute("Password", ErrorMessage = "Passwords don't match.")]
        public string RepeatPassword { get; set; }
        [Required(ErrorMessage = "Age is required")]
        [Range(18, 99)]
        public int Age { get; set; }
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "email needs valid format")]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Street address is required.")]
        public string Address1 { get; set; }
        [Required(ErrorMessage = "City is required.")]
        public string City { get; set; }
        [RegularExpression(@"[a-zA-z]\d[a-zA-Z]-\d[a-zA-Z]\d", ErrorMessage = "Invalid format")]
        [Required(ErrorMessage = "Enter a proper Postal Code")]
        public string Mailcode { get; set; }
        [Required(ErrorMessage = "Country is required.")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Credit Card is required.")]
        public string CreditcardType { get; set; }
        [Required(ErrorMessage = "Region is required.")]
        public string Region { get; set; }
    }
}

C#/CaseStudy/CaseStudy/Controllers/RegisterController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using CaseStudy.Models;
using CaseStudy.Utils;

namespace CaseStudy.Controllers
{
    public class RegisterController : Controller
    {
        UserManager<ApplicationUser> _usrMgr;
        SignInManager<ApplicationUser> _signInMgr;
        public RegisterController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _usrMgr = userManager;
            _signInMgr = signInManager;
        }
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        //
        // POST:/Register/Register
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await _usrMgr.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInMgr.SignInAsync(user, isPersistent: false);
                    HttpContext.Session.SetString(SessionVars.LoginStatus, "logged on as " + model.Email);
                    HttpContext.Session.SetString(SessionVars.Message, "Registered, logged on as " + model.Email);
                }
                else
                {
                    ViewBag.message = "registration failed - " + result.Errors.First().Description;
                    return View("Index");
                }
            }
            return Redirect("/Home");
        }
    }
}

C#/CaseStudy/CaseStudy/Views/Register/Index.cshtml
@model RegisterViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="text-center padTop10">
    <h6>&copy;Info3067 - 2017</h6>
    <br />
    <h4>@ViewBag.Message</h4>
</div>
<!-- modal code -->
<div class="modal" id="register_popup" style="background-color:#B0E0E6;">
    <div class="modal-dialog">
        <div class="modal-content col-xs-12">
            <div class="modal-header">
                <a href="" style="font-size:xx-large" data-dismiss="modal" class="pull-right">X</a>
                <div class="text-center">
                    <h3>Please Register!</h3>
                </div>
            </div>
            <div class="modal-body loginbody">
                <form asp-controller="Register" asp-action="Register" method="post" class="form-horizontal" role="form" id="registerForm">
                    <div class="tabbable" id="myTabs">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#personal" data-toggle="tab">Demographic</a></li>
                            <li><a href="#address" data-toggle="tab">Address</a></li>
                            <li><a href="#account" data-toggle="tab">Account</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="personal">
                                <div class="form-group" style="padding-left:5%;padding-top:5%;">
                                    <label asp-for="Firstname" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Firstname" class="form-control" placeholder="First Name" />
                                        <span asp-validation-for="Firstname" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group" style="padding-left:5%;">
                                    <label asp-for="Lastname" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Lastname" class="form-control" placeholder="Last Name" />
                                        <span asp-validation-for="Lastname" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group" style="padding-left:5%;">
                                    <label asp-for="Age" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Age" class="form-control" placeholder="Age" />
                                        <span asp-validation-for="Age" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group" style="padding-left:5%;">
                                    <label asp-for="CreditcardType" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="CreditcardType" class="form-control" placeholder="Credit Card Type" />
                                        <span asp-validation-for="CreditcardType" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="address">
                                <div class="form-group" style="padding-top:5%;">
                                    <label asp-for="Address1" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Address1" class="form-control" placeholder="Enter Address" />
                                        <span asp-validation-for="Address1" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="City" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="City" class="form-control" placeholder="Enter City" />
                                        <span asp-validation-for="City" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Region" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Region" class="form-control" placeholder="Enter Region" />
                                        <span asp-validation-for="Region" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Country" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Country" class="form-control" placeholder="Enter Country" />
                                        <span asp-validation-for="Country" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Mailcode" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Mailcode" class="form-control" placeholder="Enter Postal Code" />
                                        <span asp-validation-for="Mailcode" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="account">
                                <div class="form-group" style="padding-top:5%;">
                                    <label asp-for="UserName" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="UserName" class="form-control" placeholder="Enter UserName" />
                                        <span asp-validation-for="UserName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group" style="padding-top:5%;">
                                    <label asp-for="Email" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Email" type="email" class="form-control" placeholder="Enter valid Email" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Password" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Password" type="password" class="form-control" placeholder="Enter password" />
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="RepeatPassword" class="col-xs-4 control-label">Repeat PW</label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="RepeatPassword" type="password" class="form-control" placeholder="Enter same password" />
                                        <span asp-validation-for="RepeatPassword" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12 text-center">
                                        <button type="submit" class="btn btn-default">Register</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div><!-- modal-body -->
            <div class="modal-footer" id="footer">
                <h4>@ViewBag.Message</h4>
            </div><!-- modal-footer-->
        </div><!--modal-content-->
    </div><!--modal-dialog-->
</div><!--modal-->