C#/CaseStudy/CaseStudy/Models/Brand.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CaseStudy.Models
{
    public class Brand
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [Column(TypeName = "timestamp")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [MaxLength(8)]
        public byte[] Timer { get; set; }
    }
}

C#/CaseStudy/CaseStudy/Models/BrandViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System;
using System.ComponentModel.DataAnnotations;

namespace CaseStudy.Models
{
    public class BrandViewModel
    {
        private List<Brand> _brands;
        public IEnumerable<Product> Products { get; set; }
        [Required]
        public int Qty { get; set; }
        public string SelectedProductId { get; set; }
        public string BrandName { get; set; }
        public int BrandId { get; set; }
        public IEnumerable<SelectListItem> GetBrands()
        {
            return _brands.Select(brand => new SelectListItem { Text = brand.Name, Value = brand.Id.ToString() });
        }
        public void SetBrands(List<Brand> brands)
        {
            _brands = brands;
        }
    }
}

C#/CaseStudy/CaseStudy/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using CaseStudy.Models;
using System.Collections.Generic;
using CaseStudy.Utils;
using System;

namespace CaseStudy.Controllers
{
    public class BrandController : Controller
    {
        AppDbContext _db;
        public BrandController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index(BrandViewModel vm)
        {
            // Only build the catalogue once
            if (HttpContext.Session.Get<List<Brand>>(SessionVars.Brands) == null)
            {
                // no session information so let's go to the database
                try
                {
                    BrandModel categoryModel = new BrandModel(_db);
                    // now load the categories
                    List<Brand> categories = categoryModel.GetAll();
                    HttpContext.Session.Set<List<Brand>>(SessionVars.Brands, categories);
                    vm.SetBrands(categories);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Catalogue Problem - " + ex.Message;
                }
            }
            else
            {
                // no need to go back to the database as information is already in the session
                vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
                ProductModel itemModel = new ProductModel(_db);
                vm.Products = itemModel.GetAllByBrand(vm.BrandId);
            }
            return View(vm);
        }
        
        public IActionResult SelectBrand(BrandViewModel vm)
        {
            BrandModel brandModel = new BrandModel(_db);
            ProductModel productModel = new ProductModel(_db);
            List<Product> products = productModel.GetAllByBrand(vm.BrandId);
            List<ProductViewModel> productViewModels = new List<ProductViewModel>();
            if(products.Count > 0)
            {
                foreach(Product product in products)
                {
                    ProductViewModel productViewModel = new ProductViewModel();
                    productViewModel.Qty = 0;
                    productViewModel.QtyOnBackOrder = product.QtyOnBackOrder;
                    productViewModel.QtyOnHand = product.QtyOnHand;
                    productViewModel.Description = product.Description;
                    productViewModel.Id = product.Id;
                    productViewModel.BrandName = brandModel.GetName(product.BrandId);
                    productViewModel.GraphicName = product.GraphicName;
                    productViewModel.CostPrice = product.CostPrice;
                    productViewModel.MSRP = product.MSRP;
                    productViewModel.BrandId = product.BrandId;
                    productViewModel.ProductName = product.ProductName;
                    productViewModels.Add(productViewModel);
                }
                ProductViewModel[] myItems = productViewModels.ToArray();
                HttpContext.Session.Set<ProductViewModel[]>(SessionVars.Items, myItems);
            }
            vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            return View("Index", vm);
        }
        [HttpPost]
        public ActionResult SelectItem(BrandViewModel vm)
        {
            Dictionary<string, object> cart;
            if (HttpContext.Session.Get<Dictionary<string, Object>>(SessionVars.Cart) == null)
            {
                cart = new Dictionary<string, object>();
            }
            else
            {
                cart = HttpContext.Session.Get<Dictionary<string, object>>(SessionVars.Cart);
            }
            ProductViewModel[] items = HttpContext.Session.Get<ProductViewModel[]>(SessionVars.Items);
            String retMsg = "";
            foreach (ProductViewModel item in items)
            {
                if (item.Id == vm.SelectedProductId)
                {
                    if (vm.Qty > 0) // update only selected item
                    {
                        item.Qty = vm.Qty;
                        retMsg = vm.Qty + " - item(s) Added!";
                        cart[item.Id] = item;
                    }
                    else
                    {
                        item.Qty = 0;
                        cart.Remove(item.Id);
                        retMsg = "item(s) Removed!";
                    }
                    vm.BrandId = item.BrandId;
                    break;
                }
            }
            ViewBag.AddMessage = retMsg;
            HttpContext.Session.Set<Dictionary<string, Object>>(SessionVars.Cart, cart);
            vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            return PartialView("AddToCartPartial");
        }
    }
}

C#/CaseStudy/CaseStudy/Views/Brand/AddToCartPartial.cshtml
@ViewBag.AddMessage

C#/CaseStudy/CaseStudy/Views/Brand/Index.cshtml
@model BrandViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="col-sm-2 col-xs-12">&nbsp;</div>
<div class="text-center col-sm-8 col-xs-12">
    <form asp-controller="Brand" asp-action="SelectBrand" method="post">
        <div class="col-sm-4 col-xs-12">&nbsp;</div>
        <div class="col-sm-4 col-xs-12" style="padding-bottom:5%;">
            <img src="~/images/brands.svg" height="100" width="100" />
            <select asp-for="BrandId" asp-items="@Model.GetBrands()"
                    class="form-group form-control" onchange="this.form.submit();" style="top:35px;position:relative;padding:5px;">
                <option selected style="display:none;">Select Brand</option>
            </select>
        </div>
        <div class="col-sm-4 col-xs-12">&nbsp;</div>
    <supercart supercart="@Model.BrandId"></supercart>
    </form>
</div>

<div class="modal" id="details_popup" style="background-color:#B0E0E6;">
    <div class="modal-dialog">
        <div class="modal-content col-xs-12">
            <div class="modal-body">
                <a href="" style="font-size:xx-large" data-dismiss="modal" class="pull-right">X</a>
                <div class="text-center">
                    <img alt="" id="detailsGraphic" /><br />
                    <h4 id="description"></h4>
                </div>
                <form id="brandForm">
                    <div class="text-center col-sm-offset-2">
                        <table>
                            <tr><td class="col-xs-2 text-left">Description</td><td class="col-xs-4 text-left" id="desc"></td></tr>
                            <tr><td class="col-xs-2 text-left">Cost Price</td><td class="col-xs-4 text-left" id="cost"></td></tr>
                            <tr><td class="col-xs-2 text-left">Qty:</td><td class="col-xs-4 text-left"><input asp-for="Qty" type="number" maxlength="3" size="3" style="width: 50px;" id="qty" /><input asp-for="SelectedProductId" type="hidden" id="detailsId" /></td></tr>
                            <tr><td colspan="2">&nbsp;</td></tr>
                        </table>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-sm btn-default" id="modalbtn">Add To Cart</button>
                        <button id="btnRemove" type="submit" class="btn-sm btn btn-danger">Remove Item</button>
                        <a href="/Cart" class="btn btn-sm btn-success">View Cart</a>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div id="results" class="text-center">
                    @ViewBag.AddMessage
                </div>
            </div>
        </div><!--modal-content-->
    </div><!--modal-dialog-->
</div><!--modal-->